<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Indicator Report</title>
    <style>
        body {
            font-family: 'Times New Roman', Times, serif;
            color: black;
            text-align: justify;
            line-height: 1.5;
        }

        .container {
            width: 100%;
            margin: 0 auto;
        }

        .card {
            padding: 0px;
        }

        .card-title {
            font-size: 25px;
            font-weight: bold;
        }

        .card-body {
            padding: 0px;
        }

        .row {
            display: flex;
        }

        .col-sm-4,
        .col-sm-8 {
            font-size: 18px;
        }

        .col-sm-4 {
            width: 33.33%;
            font-weight: bold;
        }

        .col-sm-8 {
            width: 66.67%;
        }

        .form-control {
            padding: 0px;
            font-size: 18px;
        }

        .badge {
            background-color: #28a745;
            color: white;
            padding: 5px;
            border-radius: 3px;
        }

        .text-success {
            color: #28a745;
            font-size: 22px;
        }

        hr {
            border: 0;
        }

        p {
            margin: 0;
            font-size: 18px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            padding: 0px;
            border: 1px solid #ccc;
            font-size: 17px;
        }

        .title {
            text-align: center;
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .subtitle {
            text-align: center;
            font-size: 18px;
            margin-bottom: 20px;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>

<body>
    <div class="container">
        <!-- Logos Section -->
        <div class="logos" style="text-align: center; margin-bottom: 20px;">
            @foreach($organisations as $organization)
            <img src="{{$organization['logo']}}" alt="First Organization Logo" style="height: 150px; margin-right: 20px;">
            @endforeach
            
        </div>

        <!-- Report Title -->
        <div class="title">Indicator Report</div>

        <!-- Subtitle with additional information -->
        <div class="subtitle">
            <p>Generated by DataCities M & E Monitor</p>
            <p>Date: {{ date('Y-m-d') }}</p>
            <p>Time: {{ date('H:i:s') }}</p>
        </div>
        <div class="page-break"></div>
        
        <div class="card">
            <div class="card-title">Indicator Details</div>
            <div class="card-body">
                <table class="table table-bordered" style="margin: 0; padding: 0; border-collapse: collapse;">
                    <tr>
                        <th>Indicator Title</th>
                        <td>{{$indicatorDetails['indicator_title']}}</td>
                    </tr>
                    <tr>
                        <th>Indicator Definition</th>
                        <td>{{$indicatorDetails['definition']}}</td>
                    </tr>
                    <tr>
                        <th>Metrics</th>
                        <td>Baseline: {{$indicatorDetails['baseline']}}<br>Target: {{$indicatorDetails['target']}}</td>
                    </tr>
                    <tr>
                        <th>Data Source</th>
                        <td>{{$indicatorDetails['data_source']}}</td>
                    </tr>
                    <tr>
                        <th>Responsible</th>
                        <td>{{$indicatorDetails['responsible']}}</td>
                    </tr>
                    <tr>
                        <th>Reports are submitted to</th>
                        <td>{{$indicatorDetails['reporting']}}</td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="card">
            <div class="card-title">Responses For This Indicator</div>
            <div class="card-body">
                @foreach($responses as $response)
                <table>
                    <tr>
                        <th colspan="2">
                            <span class="badge">{{$response['response_tag_label']}} from {{$response['name']}}</span>
                        </th>
                    </tr>
                    <tr>
                        <td><strong>Baseline:</strong> {{$response['baseline']}}</td>
                        <td><strong>Current:</strong> {{$response['current']}}</td>
                    </tr>
                    <tr>
                        <td><strong>Target:</strong> {{$response['target']}}</td>
                        <td><strong>Progress:</strong> {{$response['progress']}}%</td>
                    </tr>
                    @php
                    $notesContent = trim(strip_tags($response['notes'], '<p><br>'));
                        $lessonsContent = trim(strip_tags($response['lessons'], '
                    <p><br>'));
                        $recommendationsContent = trim(strip_tags($response['recommendations'], '
                    <p><br>'));
                        @endphp

                        @if(!empty($notesContent) && $notesContent !== '
                    <p><br></p>')
                    <tr>
                        <td colspan="2">
                            <h5 class="text-success">Notes Taken</h5>
                            <p>{!! $response['notes'] !!}</p>
                        </td>
                    </tr>
                    @endif

                    @if(!empty($lessonsContent) && $lessonsContent !== '<p><br></p>')
                    <tr>
                        <td colspan="2">
                            <h5 class="text-success">Lessons learnt</h5>
                            <p>{!! $response['lessons'] !!}</p>
                        </td>
                    </tr>
                    @endif

                    @if(!empty($recommendationsContent) && $recommendationsContent !== '<p><br></p>')
                    <tr>
                        <td colspan="2">
                            <h5 class="text-success">Recommendations</h5>
                            <p>{!! $response['recommendations'] !!}</p>
                        </td>
                    </tr>
                    @endif
                </table>
                @endforeach
            </div>
        </div>
    </div>
</body>

</html>