<?php echo $__env->make('partials/header', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

<?php echo $__env->make('partials/topBar', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>;

<?php echo $__env->make('partials/leftPane', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>;

<main id="main" class="main">
  <section class="section">
    <div class="row g-0">
      <div class="col-lg-12">

        <div class="card">
          <div class="d-flex  align-items-center  px-3">
            <div class="pagetitle p-2 order-0 w-50">
              <h1 class="py-1">Baby Coaches ticket payment</h1>
              
              <nav>
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="/<?php echo e($appName); ?>/dashboard/">Dashboard</a></li>
                  <li class="breadcrumb-item active">Pay Now</li>
                </ol>
              </nav>
            </div>

            <div class="buttons-container w-50">
              <?php if($role == "Administrator"): ?>
              <!-- <a class="btn btn-secondary btn-sm" href="localhost://"> <i class="bi bi-file-earmark-pdf px-1"></i> Print PDF</a>
                    <a class="btn btn-info btn-sm text-light" href="localhost://">Export CSV</a> -->

              <?php endif; ?>

            </div>
          </div>
          <hr class="mx-4">

          <div class="card-body">


            <?php

           
            require_once('../TicketReservationSystem/vendor/pesapal/pesapal/OAuth.php');
            require_once('../TicketReservationSystem/vendor/pesapal/db/dbconnector.php');


            // $api = 'https://demo.pesapal.com';
            $api = 'https://www.pesapal.com';

            $token = $params   = NULL;
            $iframelink     = $api . '/api/PostPesapalDirectOrderV4';


            $consumer_key     = "FtbOMHLJajpDeghNZks6g0uLi8GjGcBf";
            $consumer_secret   = "7nTLRqzlVZSkagTDvi7jChURQaU=";

            $signature_method  = new OAuthSignatureMethod_HMAC_SHA1();
            $consumer       = new OAuthConsumer($consumer_key, $consumer_secret);

            //get form details

            $ref  =  str_repeat('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789', 5);
            $unique_reference  =  substr(str_shuffle($ref), 0, 10);


            $amount       =  $amount;
            $desc         = "Baby Coach Online Ticket Payments";
            $type         = 'MERCHANT';
            $name         =  $user_data['name'];
            $email         =  $user_data['email'];
            $phonenumber  =  $user_data['phone'];
            $currency     = "UGX";
            $reference     =  $unique_reference; //unique transaction id, generated by merchant.
            $callback_url   = 'http://localhost/TicketReservationSystem/routes/tickets/pay/thankyou/'; //URL user to be redirected to after payment

            $data = [
              'user_id' => $userId, 'bookID' => $bookID,
              'amount' => $amount, 'name' => $name,
              'phone_number' => $phonenumber,
              'currency' => $currency, 'reference' => $unique_reference, 'email' => $email
            ];

            //Record order in your database.
            $database = new pesapalDatabase();
            $database->store($data);

            $post_xml  = "<?xml version=\"1.0\" encoding=\"utf-8\"?>
				   <PesapalDirectOrderInfo 
						xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" 
					  	xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" 
					  	Currency=\"" . $currency . "\" 
					  	Amount=\"" . $amount . "\" 
					  	Description=\"" . $desc . "\" 
					  	Type=\"" . $type . "\" 
					  	Reference=\"" . $reference . "\" 
					  	Name=\"" . $name . "\" 
					  	Email=\"" . $email . "\" 
					  	PhoneNumber=\"" . $phonenumber . "\" 
					  	xmlns=\"http://www.pesapal.com\" />";
            $post_xml = htmlentities($post_xml);

            $iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
            $iframe_src->set_parameter("oauth_callback", $callback_url);
            $iframe_src->set_parameter("pesapal_request_data", $post_xml);
            $iframe_src->sign_request($signature_method, $consumer, $token);

            ?>

            <?php echo $__env->make('partials.pay', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
          </div>
        </div>

  </section>

  </div>

  </div>
  </div>
  </div>
</main>
  <?php echo $__env->make('partials.footer', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

  <script>
    $(document).ready(function() {
      function referenceShuffle(val) {
        if (document.getElementById('ref').checked) {
          document.getElementById("refholder").style.visibility = "visible";
        } else {
          document.getElementById("refholder").style.visibility = "hidden";
        }
      }
    })
  </script>


  </body>

  </html>